
//from SDL_Keycode

#define TED_KEY_EXTENDED_MASK          (1u << 29)
#define TED_KEY_SCANCODE_MASK          (1u << 30)
#define TED__SCANCODE_TO_KEYCODE(X)  (X | TED_KEY_SCANCODE_MASK)

#define TED_KEY_UNKNOWN                0x00000000u /**< 0 */
#define TED_KEY_RETURN                 0x0000000du /**< '\r' */
#define TED_KEY_ESCAPE                 0x0000001bu /**< '\x1B' */
#define TED_KEY_BACKSPACE              0x00000008u /**< '\b' */
#define TED_KEY_TAB                    0x00000009u /**< '\t' */
#define TED_KEY_SPACE                  0x00000020u /**< ' ' */
#define TED_KEY_EXCLAIM                0x00000021u /**< '!' */
#define TED_KEY_DBLAPOSTROPHE          0x00000022u /**< '"' */
#define TED_KEY_HASH                   0x00000023u /**< '#' */
#define TED_KEY_DOLLAR                 0x00000024u /**< '$' */
#define TED_KEY_PERCENT                0x00000025u /**< '%' */
#define TED_KEY_AMPERSAND              0x00000026u /**< '&' */
#define TED_KEY_APOSTROPHE             0x00000027u /**< '\'' */
#define TED_KEY_LEFTPAREN              0x00000028u /**< '(' */
#define TED_KEY_RIGHTPAREN             0x00000029u /**< ')' */
#define TED_KEY_ASTERISK               0x0000002au /**< '*' */
#define TED_KEY_PLUS                   0x0000002bu /**< '+' */
#define TED_KEY_COMMA                  0x0000002cu /**< ',' */
#define TED_KEY_MINUS                  0x0000002du /**< '-' */
#define TED_KEY_PERIOD                 0x0000002eu /**< '.' */
#define TED_KEY_SLASH                  0x0000002fu /**< '/' */
#define TED_KEY_0                      0x00000030u /**< '0' */
#define TED_KEY_1                      0x00000031u /**< '1' */
#define TED_KEY_2                      0x00000032u /**< '2' */
#define TED_KEY_3                      0x00000033u /**< '3' */
#define TED_KEY_4                      0x00000034u /**< '4' */
#define TED_KEY_5                      0x00000035u /**< '5' */
#define TED_KEY_6                      0x00000036u /**< '6' */
#define TED_KEY_7                      0x00000037u /**< '7' */
#define TED_KEY_8                      0x00000038u /**< '8' */
#define TED_KEY_9                      0x00000039u /**< '9' */
#define TED_KEY_COLON                  0x0000003au /**< ':' */
#define TED_KEY_SEMICOLON              0x0000003bu /**< ';' */
#define TED_KEY_LESS                   0x0000003cu /**< '<' */
#define TED_KEY_EQUALS                 0x0000003du /**< '=' */
#define TED_KEY_GREATER                0x0000003eu /**< '>' */
#define TED_KEY_QUESTION               0x0000003fu /**< '?' */
#define TED_KEY_AT                     0x00000040u /**< '@' */
#define TED_KEY_LEFTBRACKET            0x0000005bu /**< '[' */
#define TED_KEY_BACKSLASH              0x0000005cu /**< '\\' */
#define TED_KEY_RIGHTBRACKET           0x0000005du /**< ']' */
#define TED_KEY_CARET                  0x0000005eu /**< '^' */
#define TED_KEY_UNDERSCORE             0x0000005fu /**< '_' */
#define TED_KEY_GRAVE                  0x00000060u /**< '`' */
#define TED_KEY_A                      0x00000061u /**< 'a' */
#define TED_KEY_B                      0x00000062u /**< 'b' */
#define TED_KEY_C                      0x00000063u /**< 'c' */
#define TED_KEY_D                      0x00000064u /**< 'd' */
#define TED_KEY_E                      0x00000065u /**< 'e' */
#define TED_KEY_F                      0x00000066u /**< 'f' */
#define TED_KEY_G                      0x00000067u /**< 'g' */
#define TED_KEY_H                      0x00000068u /**< 'h' */
#define TED_KEY_I                      0x00000069u /**< 'i' */
#define TED_KEY_J                      0x0000006au /**< 'j' */
#define TED_KEY_K                      0x0000006bu /**< 'k' */
#define TED_KEY_L                      0x0000006cu /**< 'l' */
#define TED_KEY_M                      0x0000006du /**< 'm' */
#define TED_KEY_N                      0x0000006eu /**< 'n' */
#define TED_KEY_O                      0x0000006fu /**< 'o' */
#define TED_KEY_P                      0x00000070u /**< 'p' */
#define TED_KEY_Q                      0x00000071u /**< 'q' */
#define TED_KEY_R                      0x00000072u /**< 'r' */
#define TED_KEY_S                      0x00000073u /**< 's' */
#define TED_KEY_T                      0x00000074u /**< 't' */
#define TED_KEY_U                      0x00000075u /**< 'u' */
#define TED_KEY_V                      0x00000076u /**< 'v' */
#define TED_KEY_W                      0x00000077u /**< 'w' */
#define TED_KEY_X                      0x00000078u /**< 'x' */
#define TED_KEY_Y                      0x00000079u /**< 'y' */
#define TED_KEY_Z                      0x0000007au /**< 'z' */
#define TED_KEY_LEFTBRACE              0x0000007bu /**< '{' */
#define TED_KEY_PIPE                   0x0000007cu /**< '|' */
#define TED_KEY_RIGHTBRACE             0x0000007du /**< '}' */
#define TED_KEY_TILDE                  0x0000007eu /**< '~' */
#define TED_KEY_DELETE                 0x0000007fu /**< '\x7F' */
#define TED_KEY_PLUSMINUS              0x000000b1u /**< '\xB1' */
#define TED_KEY_CAPSLOCK               0x40000039u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_CAPSLOCK) */
#define TED_KEY_F1                     0x4000003au /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_F1) */
#define TED_KEY_F2                     0x4000003bu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_F2) */
#define TED_KEY_F3                     0x4000003cu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_F3) */
#define TED_KEY_F4                     0x4000003du /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_F4) */
#define TED_KEY_F5                     0x4000003eu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_F5) */
#define TED_KEY_F6                     0x4000003fu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_F6) */
#define TED_KEY_F7                     0x40000040u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_F7) */
#define TED_KEY_F8                     0x40000041u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_F8) */
#define TED_KEY_F9                     0x40000042u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_F9) */
#define TED_KEY_F10                    0x40000043u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_F10) */
#define TED_KEY_F11                    0x40000044u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_F11) */
#define TED_KEY_F12                    0x40000045u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_F12) */
#define TED_KEY_PRINTSCREEN            0x40000046u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_PRINTSCREEN) */
#define TED_KEY_SCROLLLOCK             0x40000047u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_SCROLLLOCK) */
#define TED_KEY_PAUSE                  0x40000048u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_PAUSE) */
#define TED_KEY_INSERT                 0x40000049u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_INSERT) */
#define TED_KEY_HOME                   0x4000004au /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_HOME) */
#define TED_KEY_PAGEUP                 0x4000004bu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_PAGEUP) */
#define TED_KEY_END                    0x4000004du /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_END) */
#define TED_KEY_PAGEDOWN               0x4000004eu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_PAGEDOWN) */
#define TED_KEY_RIGHT                  0x4000004fu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_RIGHT) */
#define TED_KEY_LEFT                   0x40000050u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_LEFT) */
#define TED_KEY_DOWN                   0x40000051u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_DOWN) */
#define TED_KEY_UP                     0x40000052u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_UP) */
#define TED_KEY_NUMLOCKCLEAR           0x40000053u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_NUMLOCKCLEAR) */
#define TED_KEY_KP_DIVIDE              0x40000054u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_DIVIDE) */
#define TED_KEY_KP_MULTIPLY            0x40000055u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_MULTIPLY) */
#define TED_KEY_KP_MINUS               0x40000056u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_MINUS) */
#define TED_KEY_KP_PLUS                0x40000057u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_PLUS) */
#define TED_KEY_KP_ENTER               0x40000058u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_ENTER) */
#define TED_KEY_KP_1                   0x40000059u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_1) */
#define TED_KEY_KP_2                   0x4000005au /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_2) */
#define TED_KEY_KP_3                   0x4000005bu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_3) */
#define TED_KEY_KP_4                   0x4000005cu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_4) */
#define TED_KEY_KP_5                   0x4000005du /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_5) */
#define TED_KEY_KP_6                   0x4000005eu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_6) */
#define TED_KEY_KP_7                   0x4000005fu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_7) */
#define TED_KEY_KP_8                   0x40000060u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_8) */
#define TED_KEY_KP_9                   0x40000061u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_9) */
#define TED_KEY_KP_0                   0x40000062u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_0) */
#define TED_KEY_KP_PERIOD              0x40000063u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_PERIOD) */
#define TED_KEY_APPLICATION            0x40000065u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_APPLICATION) */
#define TED_KEY_POWER                  0x40000066u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_POWER) */
#define TED_KEY_KP_EQUALS              0x40000067u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_EQUALS) */
#define TED_KEY_F13                    0x40000068u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_F13) */
#define TED_KEY_F14                    0x40000069u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_F14) */
#define TED_KEY_F15                    0x4000006au /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_F15) */
#define TED_KEY_F16                    0x4000006bu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_F16) */
#define TED_KEY_F17                    0x4000006cu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_F17) */
#define TED_KEY_F18                    0x4000006du /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_F18) */
#define TED_KEY_F19                    0x4000006eu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_F19) */
#define TED_KEY_F20                    0x4000006fu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_F20) */
#define TED_KEY_F21                    0x40000070u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_F21) */
#define TED_KEY_F22                    0x40000071u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_F22) */
#define TED_KEY_F23                    0x40000072u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_F23) */
#define TED_KEY_F24                    0x40000073u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_F24) */
#define TED_KEY_EXECUTE                0x40000074u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_EXECUTE) */
#define TED_KEY_HELP                   0x40000075u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_HELP) */
#define TED_KEY_MENU                   0x40000076u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_MENU) */
#define TED_KEY_SELECT                 0x40000077u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_SELECT) */
#define TED_KEY_STOP                   0x40000078u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_STOP) */
#define TED_KEY_AGAIN                  0x40000079u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_AGAIN) */
#define TED_KEY_UNDO                   0x4000007au /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_UNDO) */
#define TED_KEY_CUT                    0x4000007bu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_CUT) */
#define TED_KEY_COPY                   0x4000007cu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_COPY) */
#define TED_KEY_PASTE                  0x4000007du /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_PASTE) */
#define TED_KEY_FIND                   0x4000007eu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_FIND) */
#define TED_KEY_MUTE                   0x4000007fu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_MUTE) */
#define TED_KEY_VOLUMEUP               0x40000080u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_VOLUMEUP) */
#define TED_KEY_VOLUMEDOWN             0x40000081u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_VOLUMEDOWN) */
#define TED_KEY_KP_COMMA               0x40000085u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_COMMA) */
#define TED_KEY_KP_EQUALSAS400         0x40000086u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_EQUALSAS400) */
#define TED_KEY_ALTERASE               0x40000099u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_ALTERASE) */
#define TED_KEY_SYSREQ                 0x4000009au /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_SYSREQ) */
#define TED_KEY_CANCEL                 0x4000009bu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_CANCEL) */
#define TED_KEY_CLEAR                  0x4000009cu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_CLEAR) */
#define TED_KEY_PRIOR                  0x4000009du /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_PRIOR) */
#define TED_KEY_RETURN2                0x4000009eu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_RETURN2) */
#define TED_KEY_SEPARATOR              0x4000009fu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_SEPARATOR) */
#define TED_KEY_OUT                    0x400000a0u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_OUT) */
#define TED_KEY_OPER                   0x400000a1u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_OPER) */
#define TED_KEY_CLEARAGAIN             0x400000a2u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_CLEARAGAIN) */
#define TED_KEY_CRSEL                  0x400000a3u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_CRSEL) */
#define TED_KEY_EXSEL                  0x400000a4u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_EXSEL) */
#define TED_KEY_KP_00                  0x400000b0u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_00) */
#define TED_KEY_KP_000                 0x400000b1u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_000) */
#define TED_KEY_THOUSANDSSEPARATOR     0x400000b2u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_THOUSANDSSEPARATOR) */
#define TED_KEY_DECIMALSEPARATOR       0x400000b3u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_DECIMALSEPARATOR) */
#define TED_KEY_CURRENCYUNIT           0x400000b4u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_CURRENCYUNIT) */
#define TED_KEY_CURRENCYSUBUNIT        0x400000b5u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_CURRENCYSUBUNIT) */
#define TED_KEY_KP_LEFTPAREN           0x400000b6u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_LEFTPAREN) */
#define TED_KEY_KP_RIGHTPAREN          0x400000b7u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_RIGHTPAREN) */
#define TED_KEY_KP_LEFTBRACE           0x400000b8u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_LEFTBRACE) */
#define TED_KEY_KP_RIGHTBRACE          0x400000b9u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_RIGHTBRACE) */
#define TED_KEY_KP_TAB                 0x400000bau /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_TAB) */
#define TED_KEY_KP_BACKSPACE           0x400000bbu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_BACKSPACE) */
#define TED_KEY_KP_A                   0x400000bcu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_A) */
#define TED_KEY_KP_B                   0x400000bdu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_B) */
#define TED_KEY_KP_C                   0x400000beu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_C) */
#define TED_KEY_KP_D                   0x400000bfu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_D) */
#define TED_KEY_KP_E                   0x400000c0u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_E) */
#define TED_KEY_KP_F                   0x400000c1u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_F) */
#define TED_KEY_KP_XOR                 0x400000c2u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_XOR) */
#define TED_KEY_KP_POWER               0x400000c3u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_POWER) */
#define TED_KEY_KP_PERCENT             0x400000c4u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_PERCENT) */
#define TED_KEY_KP_LESS                0x400000c5u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_LESS) */
#define TED_KEY_KP_GREATER             0x400000c6u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_GREATER) */
#define TED_KEY_KP_AMPERSAND           0x400000c7u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_AMPERSAND) */
#define TED_KEY_KP_DBLAMPERSAND        0x400000c8u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_DBLAMPERSAND) */
#define TED_KEY_KP_VERTICALBAR         0x400000c9u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_VERTICALBAR) */
#define TED_KEY_KP_DBLVERTICALBAR      0x400000cau /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_DBLVERTICALBAR) */
#define TED_KEY_KP_COLON               0x400000cbu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_COLON) */
#define TED_KEY_KP_HASH                0x400000ccu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_HASH) */
#define TED_KEY_KP_SPACE               0x400000cdu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_SPACE) */
#define TED_KEY_KP_AT                  0x400000ceu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_AT) */
#define TED_KEY_KP_EXCLAM              0x400000cfu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_EXCLAM) */
#define TED_KEY_KP_MEMSTORE            0x400000d0u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_MEMSTORE) */
#define TED_KEY_KP_MEMRECALL           0x400000d1u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_MEMRECALL) */
#define TED_KEY_KP_MEMCLEAR            0x400000d2u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_MEMCLEAR) */
#define TED_KEY_KP_MEMADD              0x400000d3u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_MEMADD) */
#define TED_KEY_KP_MEMSUBTRACT         0x400000d4u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_MEMSUBTRACT) */
#define TED_KEY_KP_MEMMULTIPLY         0x400000d5u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_MEMMULTIPLY) */
#define TED_KEY_KP_MEMDIVIDE           0x400000d6u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_MEMDIVIDE) */
#define TED_KEY_KP_PLUSMINUS           0x400000d7u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_PLUSMINUS) */
#define TED_KEY_KP_CLEAR               0x400000d8u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_CLEAR) */
#define TED_KEY_KP_CLEARENTRY          0x400000d9u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_CLEARENTRY) */
#define TED_KEY_KP_BINARY              0x400000dau /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_BINARY) */
#define TED_KEY_KP_OCTAL               0x400000dbu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_OCTAL) */
#define TED_KEY_KP_DECIMAL             0x400000dcu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_DECIMAL) */
#define TED_KEY_KP_HEXADECIMAL         0x400000ddu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_KP_HEXADECIMAL) */
#define TED_KEY_LCTRL                  0x400000e0u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_LCTRL) */
#define TED_KEY_LSHIFT                 0x400000e1u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_LSHIFT) */
#define TED_KEY_LALT                   0x400000e2u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_LALT) */
#define TED_KEY_LGUI                   0x400000e3u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_LGUI) */
#define TED_KEY_RCTRL                  0x400000e4u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_RCTRL) */
#define TED_KEY_RSHIFT                 0x400000e5u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_RSHIFT) */
#define TED_KEY_RALT                   0x400000e6u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_RALT) */
#define TED_KEY_RGUI                   0x400000e7u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_RGUI) */
#define TED_KEY_MODE                   0x40000101u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_MODE) */
#define TED_KEY_SLEEP                  0x40000102u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_SLEEP) */
#define TED_KEY_WAKE                   0x40000103u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_WAKE) */
#define TED_KEY_CHANNEL_INCREMENT      0x40000104u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_CHANNEL_INCREMENT) */
#define TED_KEY_CHANNEL_DECREMENT      0x40000105u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_CHANNEL_DECREMENT) */
#define TED_KEY_MEDIA_PLAY             0x40000106u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_MEDIA_PLAY) */
#define TED_KEY_MEDIA_PAUSE            0x40000107u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_MEDIA_PAUSE) */
#define TED_KEY_MEDIA_RECORD           0x40000108u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_MEDIA_RECORD) */
#define TED_KEY_MEDIA_FAST_FORWARD     0x40000109u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_MEDIA_FAST_FORWARD) */
#define TED_KEY_MEDIA_REWIND           0x4000010au /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_MEDIA_REWIND) */
#define TED_KEY_MEDIA_NEXT_TRACK       0x4000010bu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_MEDIA_NEXT_TRACK) */
#define TED_KEY_MEDIA_PREVIOUS_TRACK   0x4000010cu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_MEDIA_PREVIOUS_TRACK) */
#define TED_KEY_MEDIA_STOP             0x4000010du /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_MEDIA_STOP) */
#define TED_KEY_MEDIA_EJECT            0x4000010eu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_MEDIA_EJECT) */
#define TED_KEY_MEDIA_PLAY_PAUSE       0x4000010fu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_MEDIA_PLAY_PAUSE) */
#define TED_KEY_MEDIA_SELECT           0x40000110u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_MEDIA_SELECT) */
#define TED_KEY_AC_NEW                 0x40000111u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_AC_NEW) */
#define TED_KEY_AC_OPEN                0x40000112u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_AC_OPEN) */
#define TED_KEY_AC_CLOSE               0x40000113u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_AC_CLOSE) */
#define TED_KEY_AC_EXIT                0x40000114u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_AC_EXIT) */
#define TED_KEY_AC_SAVE                0x40000115u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_AC_SAVE) */
#define TED_KEY_AC_PRINT               0x40000116u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_AC_PRINT) */
#define TED_KEY_AC_PROPERTIES          0x40000117u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_AC_PROPERTIES) */
#define TED_KEY_AC_SEARCH              0x40000118u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_AC_SEARCH) */
#define TED_KEY_AC_HOME                0x40000119u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_AC_HOME) */
#define TED_KEY_AC_BACK                0x4000011au /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_AC_BACK) */
#define TED_KEY_AC_FORWARD             0x4000011bu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_AC_FORWARD) */
#define TED_KEY_AC_STOP                0x4000011cu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_AC_STOP) */
#define TED_KEY_AC_REFRESH             0x4000011du /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_AC_REFRESH) */
#define TED_KEY_AC_BOOKMARKS           0x4000011eu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_AC_BOOKMARKS) */
#define TED_KEY_SOFTLEFT               0x4000011fu /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_SOFTLEFT) */
#define TED_KEY_SOFTRIGHT              0x40000120u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_SOFTRIGHT) */
#define TED_KEY_CALL                   0x40000121u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_CALL) */
#define TED_KEY_ENDCALL                0x40000122u /**< TED__SCANCODE_TO_KEYCODE(TED__SCANCODE_ENDCALL) */
#define TED_KEY_LEFT_TAB               0x20000001u /**< Extended key Left Tab */
#define TED_KEY_LEVEL5_SHIFT           0x20000002u /**< Extended key Level 5 Shift */
#define TED_KEY_MULTI_KEY_COMPOSE      0x20000003u /**< Extended key Multi-key Compose */
#define TED_KEY_LMETA                  0x20000004u /**< Extended key Left Meta */
#define TED_KEY_RMETA                  0x20000005u /**< Extended key Right Meta */
#define TED_KEY_LHYPER                 0x20000006u /**< Extended key Left Hyper */
#define TED_KEY_RHYPER                 0x20000007u /**< Extended key Right Hyper */